# Generated by Django 3.1.5 on 2021-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('tags', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='project/images')),
            ],
        ),
    ]
